### PR TITLE
fix: "import the testing package in the manager_test_helper.go"

### PR DESCRIPTION
**Pull request by yukels**
fix: the issue https://github.com/ory/ladon/issues/144

### CODE REVIEW

**Comment by jen20** [comment]
Another way to fix this with fewer changes is to add `// +build test` to the top of the offending file.

**Comment by aeneasr** [comment]
> Another way to fix this with fewer changes is to add // +build test to the top of the offending file.

I would actually prefer that solution - would you be up for a PR? :)

**Comment by jen20** [comment]
@aeneasr Done - https://github.com/ory/ladon/pull/147.

**Comment by yukels** [comment]
Hi

I saw you fixed the problem. But it still not publicly available. Please
create a new release for the latest changes.
Thanks a lot for your help!

**Comment by aeneasr** [comment]
My bad: v1.2.0

**Comment by yukels** [comment]
Thanks!

**Pull request closed without merging**
