### PR TITLE
core: addressing performance issues

### PR DESCRIPTION
**Pull request by arekkas**
This patch introduces a very simple cache (needs to be replaced with LRU and needs a lock) and also a check if regex is used, and if not a simple string match is done.

Before:

```
BenchmarkLadon/policies=10-8                2000            651439 ns/op
BenchmarkLadon/policies=100-8                200           6013814 ns/op
BenchmarkLadon/policies=1000-8                20          68589825 ns/op
BenchmarkLadon/policies=10000-8                2         892683090 ns/op
BenchmarkLadon/policies=100000-8               1        11491167597 ns/op
```

Current:

```
BenchmarkLadon/policies=10-8              300000              5959 ns/op
BenchmarkLadon/policies=100-8              30000             44384 ns/op
BenchmarkLadon/policies=1000-8              3000            516475 ns/op
BenchmarkLadon/policies=10000-8              100          13835072 ns/op
BenchmarkLadon/policies=100000-8               1        4470569157 ns/op
```

### CODE REVIEW

**Comment by arekkas** [comment]
This benchmark is skewed as each policy has a unique regexp. In real-world situations this will perform better as each policy is only compiled once, and then tested again and again.

Regarding the cache, we probably need to figure out if LRU or anything like that makes sense, because, in the case of a memory manager, we'll hit all policies on every request.

Also we need to check if SQL performs better or worse with regexp matching than Go. If it does, this will also boost real life installations as SQL is going to filter a lot of those policies.

**Comment by arekkas** [comment]
If it turns out that SQL is a bottleneck, another idea is to add a hidden flag in the SQL database for policies indicating if regexp was used and if not, just do a simple LIKE match.

**Comment by arekkas** [comment]
Another idea is to take batches of e.g. 10 policies and run each batch in it's own goroutine. This might increase CPU load, but it will decrease compute time.

**Comment by arekkas** [comment]
It would probably make a lot of sense to index the patterns, see http://dba.stackexchange.com/questions/10694/pattern-matching-with-like-similar-to-or-regular-expressions-in-postgresql

Thi could be done with a sql migration

**Comment by arekkas** [comment]
I have implemented benchmarks against databases, keep in mind that these tests boot up a docker image on a limited VM, so real world (dedicated, big sql instance) might gain much better results:

```

[mysql] 2017/03/28 16:37:46 packets.go:33: unexpected EOF
BenchmarkLadon/store=memory/policies=10-8                 200000              9106 ns/op
BenchmarkLadon/store=mysql/policies=10-8                    2000            709707 ns/op
BenchmarkLadon/store=postgres/policies=10-8                 2000           4662959 ns/op
BenchmarkLadon/store=memory/policies=100-8                 20000             74417 ns/op
BenchmarkLadon/store=mysql/policies=100-8                   1000           2997000 ns/op
BenchmarkLadon/store=postgres/policies=100-8                 100          26875696 ns/op
BenchmarkLadon/store=memory/policies=1000-8                 2000            859522 ns/op
BenchmarkLadon/store=mysql/policies=1000-8                   100          16495592 ns/op
BenchmarkLadon/store=postgres/policies=1000-8                 10         240685810 ns/op
BenchmarkLadon/store=memory/policies=10000-8                   5         292642739 ns/op
BenchmarkLadon/store=mysql/policies=10000-8                   20         159098027 ns/op
BenchmarkLadon/store=postgres/policies=10000-8                 1        1416070346 ns/op
BenchmarkLadon/store=memory/policies=100000-8                  1        4206794542 ns/op
```

I'm currently exploring different options to improve this.

**Comment by arekkas** [comment]
Another test was implemented for the SQL adapters where all policies are fetched instead of running regexp. This results in the following runtimes:

```
BenchmarkLadon/store=memory/policies=10-8                 200000              9945 ns/op
BenchmarkLadon/store=mysql/policies=10-8                    2000            864544 ns/op
BenchmarkLadon/store=postgres/policies=10-8                 2000           4525414 ns/op
BenchmarkLadon/store=memory/policies=100-8                 20000             82830 ns/op
BenchmarkLadon/store=mysql/policies=100-8                    500           3261914 ns/op
BenchmarkLadon/store=postgres/policies=100-8                 100          29053794 ns/op
BenchmarkLadon/store=memory/policies=1000-8                 2000            921784 ns/op
BenchmarkLadon/store=mysql/policies=1000-8                   100          17395813 ns/op
BenchmarkLadon/store=postgres/policies=1000-8                 10         234031649 ns/op
BenchmarkLadon/store=memory/policies=10000-8                   5         321583899 ns/op
BenchmarkLadon/store=mysql/policies=10000-8                   20         174089037 ns/op
BenchmarkLadon/store=postgres/policies=10000-8                 1        1357890621 ns/op
BenchmarkLadon/store=memory/policies=100000-8                  1        4254213798 ns/op
```

So in total this yields worse performance. In the process I found about 4 queries that could be joined to one. Additionally, it could be possible to first filter for effect and then continue with fields that are more saturated like subject / resource.

Another thing is that normalizing fields such as subject and have n:m subject/policy, effect/policy, resource/policy could save us a lot of time (and space) on duplicates.

One question is if a long query such as `SELECT FROM .. JOIN .. WHERE .. AND .. AND .. AND .. AND` yields better or worse performance.

**Comment by arekkas** [comment]
It would probably be a good idea to create a back up of the existing data and e.g. write it to disk

**Comment by dim** [comment]
Apart from SQL optimisation, I would be tempted to implement a CachingManager as a separate wrapper around any other Manager. Instead of an LRU based method, I would consider adding a Manager.AllPolicies method to the interface which the CachingManager could then use to query the underlying backend in regular intervals (e.g. every 60s) and build an in-memory manager. 

Happy to submit a PR for this

**Comment by arekkas** [comment]
I'm not sure on this, I want to keep state out of this for now. The LRU cache is by the way not for policies, only for compiled regular expressions. By the way, I was able to fix the SQL manager yesterday and it now outperforms all other managers with basically constant complexity (10 policies almost as fast as 100k policies).

**Comment by arekkas** [comment]
```

BenchmarkLadon/store=memory/policies=10-8                 500000              2721 ns/op
BenchmarkLadon/store=mysql/policies=10-8                    5000            264166 ns/op
BenchmarkLadon/store=postgres/policies=10-8                 5000            321962 ns/op
BenchmarkLadon/store=memory/policies=100-8                200000             11889 ns/op
BenchmarkLadon/store=mysql/policies=100-8                   5000            257504 ns/op
BenchmarkLadon/store=postgres/policies=100-8                3000            343637 ns/op
BenchmarkLadon/store=memory/policies=1000-8                10000            114868 ns/op
BenchmarkLadon/store=mysql/policies=1000-8                  5000            288926 ns/op
BenchmarkLadon/store=postgres/policies=1000-8               3000            569740 ns/op
BenchmarkLadon/store=memory/policies=10000-8                1000           1638827 ns/op
BenchmarkLadon/store=mysql/policies=10000-8                 5000            274984 ns/op
BenchmarkLadon/store=postgres/policies=10000-8              3000            474347 ns/op

```

**Comment by dim** [comment]
OK, looking forward to this being merged

**Comment by arekkas** [comment]
Give me a few days to write good test cases etc :)

**Comment by arekkas** [comment]
Unfortunately, there were issues with the previous benchmark resulting skewed results. I implemented a 3NF version of the SQL storage yielding currently:

```
BenchmarkLadon/store=memory/policies=10-8                 500000              2422 ns/op
BenchmarkLadon/store=mysql/policies=10-8                    2000           1453881 ns/op
BenchmarkLadon/store=postgres/policies=10-8                  300           5825037 ns/op
BenchmarkLadon/store=memory/policies=100-8                200000             11652 ns/op
BenchmarkLadon/store=mysql/policies=100-8                    200           7763211 ns/op
BenchmarkLadon/store=postgres/policies=100-8                 100          26626737 ns/op
BenchmarkLadon/store=memory/policies=1000-8                10000            103799 ns/op
BenchmarkLadon/store=mysql/policies=1000-8                    50          51620408 ns/op
```

**Comment by arekkas** [comment]
I improved the 3NF query by doing simple matches for things that aren't regular expressions:

```
BenchmarkLadon/store=memory/policies=10-8                 500000              2426 ns/op
BenchmarkLadon/store=mysql/policies=10-8                    1000           1229239 ns/op
BenchmarkLadon/store=postgres/policies=10-8                 1000           5441425 ns/op
BenchmarkLadon/store=memory/policies=100-8                200000             10900 ns/op
BenchmarkLadon/store=mysql/policies=100-8                    300           7118921 ns/op
BenchmarkLadon/store=postgres/policies=100-8                 100          24775371 ns/op
BenchmarkLadon/store=memory/policies=1000-8                10000            102500 ns/op
BenchmarkLadon/store=mysql/policies=1000-8                    50          42360108 ns/op
```
I'm currently investigating if it makes sense to throw away the 3NF (it does not seem to have very much of a positive impact. I'll also investigate if it makes more sense to throw away the massive JOIN and instead do two queries, one for search and one for fetch with id.

**Comment by arekkas** [comment]
Fetching every policy by its own and reducing the query statement's size did not work:

```

BenchmarkLadon/store=memory/policies=10-8                 500000              2398 ns/op
BenchmarkLadon/store=mysql/policies=10-8                     500           3686645 ns/op
BenchmarkLadon/store=postgres/policies=10-8                  500           8031815 ns/op
BenchmarkLadon/store=memory/policies=100-8                200000             11005 ns/op
BenchmarkLadon/store=mysql/policies=100-8                    200           7245687 ns/op
BenchmarkLadon/store=postgres/policies=100-8                 100          30372021 ns/op
BenchmarkLadon/store=memory/policies=1000-8                10000            106700 ns/op
BenchmarkLadon/store=mysql/policies=1000-8                   100          18316759 ns/op
BenchmarkLadon/store=postgres/policies=1000-8                 10         245579960 ns/op
BenchmarkLadon/store=memory/policies=10000-8                1000           1225499 ns/op
```

I compared the current benchmark with previous versions. The 3NF in fact performs MUCH better - previous benchmarks showed better results because the policies used were smaller in size.

**Comment by arekkas** [comment]
Parallelizing (30 concurrent connections) did not help either:

```
BenchmarkLadon/store=memory/policies=10-8                 500000              2923 ns/op
BenchmarkLadon/store=mysql/policies=10-8                     100          12775014 ns/op
BenchmarkLadon/store=postgres/policies=10-8                  300          22927204 ns/op
BenchmarkLadon/store=memory/policies=100-8                200000             11242 ns/op
BenchmarkLadon/store=mysql/policies=100-8                    100          16516017 ns/op
BenchmarkLadon/store=postgres/policies=100-8                  50          45011302 ns/op
BenchmarkLadon/store=memory/policies=1000-8                10000            105087 ns/op
```

**Comment by arekkas** [comment]
Further improvements on keeping the number of regexp matches low:

```
BenchmarkLadon/store=memory/policies=10-8                 500000              2467 ns/op
BenchmarkLadon/store=mysql/policies=10-8                    1000           1536664 ns/op
BenchmarkLadon/store=postgres/policies=10-8                 1000           6483077 ns/op
BenchmarkLadon/store=memory/policies=100-8                200000             11312 ns/op
BenchmarkLadon/store=mysql/policies=100-8                    500           5429853 ns/op
BenchmarkLadon/store=postgres/policies=100-8                 100          28801780 ns/op
BenchmarkLadon/store=memory/policies=1000-8                10000            103549 ns/op
BenchmarkLadon/store=mysql/policies=1000-8                   200          37489959 ns/op
BenchmarkLadon/store=postgres/policies=1000-8                 10         233467260 ns/op
BenchmarkLadon/store=memory/policies=10000-8                1000           1342500 ns/op
```

**Comment by arekkas** [comment]
Unfortunately tests keep running out of time, because the insert statements are much slower than the query statements, which is why the tests don't get past 10.000 policies.

**Comment by arekkas** [comment]
This is coming to an end! :)

**Pull request merged**
