### PR TITLE
New custom context keys equality condition

### PR DESCRIPTION
**Pull request by ericalandouglas**
Signed-off-by: Eric Douglas <eric@bridg.com>

### CODE REVIEW

**Comment by ericalandouglas** [comment]
I am hoping to support policies that look like the following in Hydra by including this new condition:

```
{
  "description": "Allow account admins full access to account resources.",
  "subjects": [
    "account-admin"
  ],
  "effect": "allow",
  "resources": [
    "rn:accounts:<[A-z0-9_-]+(:.+)?>"
  ],
  "actions": [
    "create", "read", "update", "delete"
  ],
  "conditions": {
    "account-ids": {
      "type": "ContextKeyValuesEqualCondition",
      "options": {
        "Key1": "user-account-id",
        "Key2": "resource-account-id"
      }
    }
  }
}
```

A sample context to be provided to the warden during policy check time can look like:

```
"context": {
  "account-ids": {
    "user-account-id": "account-1",
    "resource-account-id": "account-2"
  }
}
```

The context above will not satisfy the sample policy. The inclusion of this context and condition helps avoid creating more resource specific policies (scoped to specific account IDs, etc.).

**Comment by arekkas** [comment]
Hi Eric, I'm really busy at the moment and will try to give this issue some thorough thought next week!

**Comment by ericalandouglas** [comment]
Thanks @arekkas!

**Comment by ericalandouglas** [comment]
Yes, that is what I am going for here. I need to be able to supply two arbitrary values at policy check time. The original StringEqual condition requires you bake in the equality value at policy creation time.

My fork is functioning as needed with this new condition but I am open to extending it further so that it can support more than two keys. I do have some policies where I supply two of these new custom conditions, I guess that could be made more concise by having this custom condition support more than two keys.

**Comment by arekkas** [comment]
It would be awesome if you could add the functionality of having more key/value pairs :)

**Comment by arekkas** [comment]
Oh and could you please add a section to the [readme](https://github.com/ory/ladon#conditions) for this condition?

**Comment by ericalandouglas** [comment]
Thanks for reviewing, I can update the condition and README. As far as the value's type for this condition goes what might make most sense? Supporting a map with arbitrary keys doesn't seem useful as deriving which keys to check for equality won't be possible. Would an array of string pairs (pair is a simple tow-element array?) or similar be sufficient?

**Comment by ericalandouglas** [comment]
A sample context may look like:
```
"context": {
  "entity-ids": [
      ["account-1": "account-1"],
      ["site-1", "site-3"]
  ]
}
```
The above context will fail when used in the custom condition as the second pair is not equal.

**Comment by arekkas** [comment]
Yup, looks good!

**Comment by arekkas** [comment]
Oh and could you please add a test :)

**Comment by ericalandouglas** [comment]
I can add tests as well. I believe CI was broken before I opened this PR but I will make sure the tests I create pass.

**Comment by arekkas** [comment]
You can fix ci by adding

```
go_import_path: github.com/ory-am/ladon
```

to [travis.yml](https://github.com/ory/ladon/blob/master/.travis.yml) (see example from [fosite](
https://github.com/ory/fosite/blob/master/.travis.yml#L3) :)

**Comment by arekkas** [comment]
Nice! Unfortunately tests fail, see https://travis-ci.org/ory/ladon/jobs/211574993#L414-L428

**Comment by ericalandouglas** [comment]
My bad, should be all set now.

**Comment by arekkas** [comment]
Nice, thank you so much!

**Pull request merged**
