### PR TITLE
Fix typos in the example policies

### PR DESCRIPTION
**Pull request by thoslin**
I tested the example policy with a Gin restful server, it doesn't work. It turns out there's couple typo in the example:
1. Should not use square bracket in ``` <[peter|ken]>```, this would match every single character within the bracket but not peter or ken.
2. resource should be resources in ```resource:articles:ladon-introduction```

The below is how I tested the example:

Rest APIs based on Gin
```
package main

import "github.com/gin-gonic/gin"
import "github.com/ory/ladon"
import manager "github.com/ory/ladon/manager/memory"
import "net/http"

var warden = &ladon.Ladon{Manager: manager.NewMemoryManager()}

func main() {
	r := gin.Default()

	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})

	r.POST("/warden", func(c *gin.Context) {
		var req ladon.Request

		if err := c.ShouldBindJSON(&req); err == nil {
			err := warden.IsAllowed(&req)
			if err == nil {
				c.JSON(http.StatusOK, gin.H{"allowed": true})
			} else {
				c.JSON(http.StatusOK, gin.H{"allowed": false, "error": err.Error()})
			}
		}
	})

	r.POST("/policies", func(c *gin.Context) {
		var policy ladon.DefaultPolicy

		if err := c.ShouldBindJSON(&policy); err == nil {
			err := warden.Manager.Create(&policy)
			if err == nil {
				c.JSON(http.StatusOK, gin.H{"success": true})
			} else {
				c.JSON(http.StatusOK, gin.H{"success": false, "error": err.Error()})	
			}
		}
	})

	r.Run(":3000")
}
```
The test I ran, taken from the example:
```
# create policy
$ curl \
>       -X POST \
>       -H "Content-Type: application/json" \
>       -d@- \
>       "http://localhost:3000/policies" <<EOF
>         {
>           "description": "One policy to rule them all.",
>           "subjects": ["users:<[peter|ken]>", "users:maria", "groups:admins"],
>           "actions" : ["delete", "<[create|update]>"],
>           "effect": "allow",
>           "resources": [
>             "resources:articles:<.*>",
>             "resources:printer"
>           ],
>           "conditions": {
>             "remoteIP": {
>                 "type": "CIDRCondition",
>                 "options": {
>                     "cidr": "192.168.0.1/16"
>                 }
>             }
>           }
>         }
> EOF
{"success":true}
```
```
# test policy
$ curl \
>       -X POST \
>       -H "Content-Type: application/json" \
>       -d@- \
>       "http://localhost:3000/warden" <<EOF
>         {
>           "subject": "users:peter",
>           "action" : "delete",
>           "resource": "resource:articles:ladon-introduction",
>           "context": {
>             "remoteIP": "192.168.0.5"
>           }
>         }
> EOF
{"allowed":false,"error":"Request was denied by default"}

# users:p passed
curl \
>       -X POST \
>       -H "Content-Type: application/json" \
>       -d@- \
>       "http://localhost:3000/warden" <<EOF
>         {
>           "subject": "users:p",
>           "action" : "delete",
>           "resource": "resources:articles:ladon-introduction",
>           "context": {
>             "remoteIP": "192.168.0.5"
>           }
>         }
> EOF
{"allowed":true}
```
Now fix the typo and ran again:
```
$ curl \
>       -X POST \
>       -H "Content-Type: application/json" \
>       -d@- \
>       "http://localhost:3000/policies" <<EOF
>         {
>           "description": "One policy to rule them all.",
>           "subjects": ["users:<peter|ken>", "users:maria", "groups:admins"],
>           "actions" : ["delete", "<create|update>"],
>           "effect": "allow",
>           "resources": [
>             "resources:articles:<.*>",
>             "resources:printer"
>           ],
>           "conditions": {
>             "remoteIP": {
>                 "type": "CIDRCondition",
>                 "options": {
>                     "cidr": "192.168.0.1/16"
>                 }
>             }
>           }
>         }
> EOF
{"success":true}

$ curl \
>       -X POST \
>       -H "Content-Type: application/json" \
>       -d@- \
>       "http://localhost:3000/warden" <<EOF
>         {
>           "subject": "users:peter",
>           "action" : "delete",
>           "resource": "resources:articles:ladon-introduction",
>           "context": {
>             "remoteIP": "192.168.0.5"
>           }
>         }
> EOF
{"allowed":true}
```

### CODE REVIEW

**Comment by arekkas** [comment]
Right! Thanks! Could you also fix the response in the readme?

```
{
  "subject": "users:peter",
  "action" : "delete",
  "resource": "resource:articles:ladon-introduction",
  "context": {
    "remoteIP": "192.168.0.5"
  }
}
```

**Comment by thoslin** [comment]
Could you tell me which line it is? I think I have updated it all in my branch https://github.com/thoslin/ladon/tree/FixTypos.

**Comment by arekkas** [comment]
* https://github.com/ory/ladon/blame/master/README.md#L118
* https://github.com/ory/ladon/blame/master/README.md#L169
* https://github.com/ory/ladon/blame/master/README.md#L118

I think there are six in total, it's probably easiest to just do ctrl+f `resource:`

:)

**Comment by thoslin** [comment]
I'm not sure if these lines should be changed. The key "resource"  in the payload is corresponding to the resource field in your ```ladon.Request``` model:
```
type Request struct {
	// Resource is the resource that access is requested to.
	Resource string `json:"resource"`

	// Action is the action that is requested on the resource.
	Action string `json:"action"`

	// Subejct is the subject that is requesting access.
	Subject string `json:"subject"`

	// Context is the request's environmental context.
	Context Context `json:"context"`
}
```

**Comment by arekkas** [comment]
The responses have the wrong output, right? For example, [this line](https://github.com/ory/ladon/blame/master/README.md#L118) reads

```
  "resource": "resource:articles:ladon-introduction",
```

but according to you PR it should be

```
  "resource": "resource**s**:articles:ladon-introduction",
```

**Comment by thoslin** [comment]
I'm sorry. Am I missing something? The line you are referring to is on the **master** branch. I think I've already corrected them in my branch. Please check https://raw.githubusercontent.com/thoslin/ladon/FixTypos/README.md.

**Comment by arekkas** [comment]
Oh man, sorry for the confusion. For some reason I thought you changed something a different file. This happens when my head is all over the place. Sorry again and thank you for your contribution!

**Pull request merged**
